XeroAPI/Xero-NetStandard

- Xero.Api/ApplicationSettings.cs
- Xero.Api/Core/XeroCoreApi.cs
This change makes it possible to use a configuration file other than "appsettings.json"
Since the `XeroCoreApi` class requires an instance of `ApplicationSettings`, its impossible to instantiate one for use without the constructor firing which raises an Exception when "appsettings.json" doesn't exist.
> Allow custom path to appsettings.json

- Xero.Api.Example.Console/Program.cs
@MatthewMXero 
Only changes the examples therefore no need to do a release
> Makes PartnerApp() static otherwise it cannot be used.

- Xero.Api/Core/Model/Overpayment.cs
- Xero.Api/Core/Model/Prepayment.cs
At the moment I can't determine how much has been credited from each Overpayment and Prepayment against an invoice by using the api client.
A manual request to the invoice api endpoint shows there is an "AppliedAmount" field for Prepayments and Overpayments, but they need to be added to the model to be accessible from the api client. Credit Notes linked to an invoice also have the field, but it's already included in the model so no change is required there.
> Added AppliedAmount field to Prepayment and Overpayment

- Xero.Api/Common/XeroReadEndpoint.cs
- Xero.Api/Core/Endpoints/AllocationEndpoint.cs
- Xero.Api/Core/Endpoints/AssociationsEndpoint.cs
- Xero.Api/Core/Endpoints/AttachmentsEndpoint.cs
- Xero.Api/Core/Endpoints/Base/XeroCreateEndpoint.cs
- Xero.Api/Core/Endpoints/Base/XeroUpdateEndpoint.cs
- Xero.Api/Core/Endpoints/ContactGroupEndpoint.cs
- Xero.Api/Core/Endpoints/ContactsEndpoint.cs
- Xero.Api/Core/Endpoints/FilesEndpoint.cs
- Xero.Api/Core/Endpoints/FoldersEndpoint.cs
- Xero.Api/Core/Endpoints/HistoryAndNotesEndpoint.cs
- Xero.Api/Core/Endpoints/InboxEndpoint.cs
- Xero.Api/Core/Endpoints/InvoicesEndpoint.cs
- Xero.Api/Core/Endpoints/ItemsEndpoint.cs
- Xero.Api/Core/Endpoints/LinkedTransactionsEndpoint.cs
- Xero.Api/Core/Endpoints/OrganisationEndpoint.cs
- Xero.Api/Core/Endpoints/PdfEndpoint.cs
- Xero.Api/Core/Endpoints/ReportsEndpoint.cs
- Xero.Api/Core/Endpoints/SetupEndpoint.cs
- Xero.Api/Core/Endpoints/TrackingCategoriesEndpoint.cs
- Xero.Api/Core/XeroCoreApi.cs
- Xero.Api/Infrastructure/Http/XeroHttpClient.cs
- Xero.Api/Infrastructure/OAuth/OAuthTokens.cs
- Xero.Api/Payroll/AmericanPayroll.cs
- Xero.Api/Payroll/AustralianPayroll.cs
- Xero.Api/Payroll/Common/PayrollEndpoint.cs
- Xero.Api/Xero.Api.csproj
The `await` calls in this library were missing `ConfigureAwait(false)`. This will result in a deadlock when trying to [block on these methods](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) (e.g. accessing `Result`) when there's a `SynchronizationContext` (as is the case for ASP.NET Web Forms/MVC/Web API, WPF, Windows Forms, etc., though not for ASP.NET Core or Console apps).
Adding `ConfigureAwait(false)` also gives a [small performance benefit](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx).
I added the [ConfigureAwaitChecker Analyzer](https://www.nuget.org/packages/ConfigureAwaitChecker.Analyzer/) to the project to help avoid this issue re-appearing.
> Adding ConfigureAwait(false)

- Xero.Api.Example.Console/Program.cs
- Xero.Api.Example.MVC/Authenticators/PartnerMvcAuthenticator.cs
- Xero.Api.Example.MVC/Authenticators/PublicMvcAuthenticator.cs
- Xero.Api.Example.MVC/Helpers/XeroApiHelper.cs
- Xero.Api.Example.MVC/Startup.cs
- Xero.Api/IXeroApiSettings.cs
- Xero.Api/Infrastructure/Authenticators/PartnerAuthenticatorBase.cs
- Xero.Api/Infrastructure/Authenticators/TokenStoreAuthenticatorBase.cs
- Xero.Api/XeroApiAppType.cs
- Xero.Api/XeroApiSettings.cs
I changed the type of `IXeroApiSettings.AppType` from `string` to a new enum type `XeroApiAppType` to make it clearer what options are available. I also removed the seemingly redundant `IsPartnerApp` property.
> Add XeroApiAppType enum

- Xero.Api/XeroApiSettings.cs
Passing in a path filename is not ideal when the configuration has already been loaded, when debugging a .net core website its looking for  "appsettings.json" which is not saved in the build directory. Also for ease of configuration profiles e.g. "appsettings.Development.json", "appsettings.Production.json" etc.
> Use existing configuration

- Xero.Api/Payroll/Australia/Model/Timesheet.cs
In the [Payroll API documentation](https://developer.xero.com/documentation/payroll-api/timesheets) I noticed that UpdatedDateUTC was in the Timesheet response, but wasn't in the Timesheet model. To provide for this I have inherited from HasUpdatedDate, as was the style at the time.
> Added HasUpdatedDate base class to Timesheet model.

- Xero.Api/Infrastructure/Authenticators/PartnerAuthenticatorBase.cs
Add a constructor to PartnerAuthenticatorBase to accept a certificate to allow working with certificates in locations other than the file system.
> Add constructor to accept a certificate in partner application

- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
- Xero.NetStandard.OAuth2Client/src/Client/IXeroClient.cs
- Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs
A fix for: 
1. issue with PKCE method still using IHttpClientFactory dependency
2. rename RequestXeroTokenAsync() to RequestAccessTokenAsync()
3. updated IdentityModel version to 4.0.0 as requested by [this issue](https://github.com/XeroAPI/Xero-NetStandard/issues/126)
> Fix ihttpclientfactory v1 0 0 release

- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
- Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs
Revoke token method was sending access token. It is not corrected to send refresh token which will result in actual token revocation.
> fixed bug with revoke token method

- Xero.NetStandard.OAuth2/Api/ProjectApi.cs
- added PostSetupAsync method
- added ConversionBalances model
- added ConversionDate model
- added ImportSummary model
- added ImportSummaryAccounts model
- added ImportSummaryObject model
- added ImportSummaryOrganisation model
- added chargeType parameter
- added EarningRate ENUMs:
OvertimeEarnings
RegularEarnings
SalarySacrificeForKiwiSaver
Tips(Direct)
Tips(Non-Direct)
WithholdingIncome
- removed paymentMethod as a must required parameter
- added employerTaxLines in Payslip model
> generated against OAS 2.4.4

- Xero.NetStandard.OAuth2/Client/ApiClient.cs
- Xero.NetStandard.OAuth2/Client/Configuration.cs
- Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
- InterceptRequest and InterceptResponse are now protected virtual instead of partial
- Add special exception message for ApiException for rate limit exception
SDK version updated to 3.10.0
> Make Intercept methods virtual and add new case for ApiException

- Xero.NetStandard.OAuth2.sln
Adding the test project to the solution. Has the following benefits:
- Intellisense in the test project
- can run `dotnet test` from solution root directory
- running `dotnet build` will build all projects -- helps prevent against committing broken tests
> Add test project to OAuth2 solution file

- Xero.NetStandard.OAuth2.Test/Model/Accounting/InvoiceTests.cs
- Xero.NetStandard.OAuth2/Client/ApiClient.cs
Add first test for testing deserialization locally and directly.
Tests requiring a more complex JSON document can use test helpers as required.
> Add example test using CustomJsonCodec to test deserialization

- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
- Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs
Added overload method to BuildLoginUri() and BuildLoginUriPkce() to allow passing in state and/or scope:
- BuildLoginUri(string state)
- BuildLoginUri(string state, string scope)
- BuildLoginUriPkce(string codeVerifier, string state)
- BuildLoginUriPkce(string codeVerifier, string state, string scope)
> updating BuildLoginUri() and BuildLoginUriPkce() methods

- README.md
Accounting API methods now had working examples in auto-generated docs under /docs/accounting/index.html. 
Readme.md updated to include the link. 
Github pages is turned on on the repo.
> Generated SDK doc for Accounting API

- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
- Xero.NetStandard.OAuth2Client/src/Client/IXeroClient.cs
added the following interface to IXeroClient.cs as reported by [issue 337](https://github.com/XeroAPI/Xero-NetStandard/issues/337)
BuildLoginUri(string state);
BuildLoginUri(string state, string scope);
BuildLoginUriPkce(string codeVerifier, string state);
BuildLoginUriPkce(string codeVerifier, string state, string scope);
RevokeAccessTokenAsync(IXeroToken xeroToken);
Version updated to 1.3.1
> added missing interfaces in IXeroClient.cs

- docs/accounting/index.html
Fixed a casing typo in the javascript for accounting docs which was causing an issue on the documentation header
> Fixed casing in JS

- README.md
- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
- Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs
This defaults param to true, but allows you to not 'fetch connections' so that you can use client credentials with out fetching tenants for generating a marketplace billing token.
> Refactor client to support custom connections for app store

- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
Fixed an issue with some projects which use IdentityModel 5.x.x not being able to build urls with the OAuth2Client.
Fixes Issue [#384](https://github.com/XeroAPI/Xero-NetStandard/issues/384)
All tests still passing.
> Fix Issues with IdentityModel 5.x.x

- README.md
- Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
The Newtonsoft.Json package is required to build the package, unclear why it wasn't already included.
This should now be ready for release (OAuth2.Client only, SDK release is not required)
> Additional dependency required for OAuth2.Client fix

- Xero.NetStandard.OAuth2/Client/ApiClient.cs
- Xero.NetStandard.OAuth2/Client/Configuration.cs
- Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
- docs/accounting/index.html
- docs/appstore/index.html
- docs/bankfeeds/index.html
- docs/files/index.html
- docs/finance/index.html
- docs/payroll-au/index.html
- docs/payroll-nz/index.html
- docs/payroll-uk/index.html
- docs/projects/index.html
Changes to upgrade to RestSharp 108 generated by codegen, as initially proposed by @AshleyMedway in this [PR](https://github.com/XeroAPI/Xero-NetStandard/pull/439). Manually tested using the sample app with all API calls and succeeds
- Moves cookie handling logic into `Configuration` as RestSharp moves Cookie handling logic out of `RestRequest` class (into `RestClient`)
- `IRestResponse` and `IRestRequest` are deprecated and use `RestResponse` and `RestResponse`
- Implements `IRestSerializer` interface and implements respective methods/properties
> Restsharp version bump

- Xero.NetStandard.OAuth2.Test/Api/AccountingApiTests.cs
- [OAS 2.33.0](https://github.com/XeroAPI/Xero-OpenAPI/commit/460899330ec87a6037058e852c885513273dfc61#diff-b53ec75ca0b7c2853cabb35cc15832cea39975d3e7e5200a2162aff3b7e90227R3419) altered parameters of `CreateBrandingThemePaymentService` causing unit test to fail. 
- `PaymentServices` is now provided instead of `PaymentService`
> Fixed CreateBrandingThemePaymentServicesTest

- Xero.NetStandard.OAuth2.Test/Xero.NetStandard.OAuth2.Test.csproj
- Xero.NetStandard.OAuth2/Client/ApiClient.cs
- Xero.NetStandard.OAuth2/Client/Configuration.cs
- Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
Build from OAS 2.40.1
Updates RestSharp dependency to 110.2.0. 
Bug Fixes
1. https://github.com/XeroAPI/Xero-NetStandard/issues/495
2. https://github.com/XeroAPI/Xero-NetStandard/issues/484
3. https://github.com/XeroAPI/Xero-NetStandard/issues/442
4. https://github.com/XeroAPI/Xero-NetStandard/issues/472
> Updates RestSharp package to 110.2.0
