Xero.Api.Example.MVC/Controllers/HomeSettingController.cs
Xero.Api.Example.MVC/Helpers/XeroApiHelper.cs
Xero.Api.Example.MVC/Startup.cs
Xero.Api.Example.MVC/Views/HomeSetting/Authorize.cshtml
Xero.Api.Example.MVC/Views/HomeSetting/Connect.cshtml
Xero.Api.Example.MVC/Views/HomeSetting/Index.cshtml
Xero.Api.Example.MVC/Views/HomeSetting/NoAuthorized.cshtml
Xero.Api.Example.MVC/Xero.Api.Example.MVC.csproj
Xero.Api/ApplicationSettings.cs
Xero.Api/Core/XeroCoreApi.cs

See issue 3 
https://github.com/XeroAPI/Xero-NetStandard/issues/3

Changes to the api to allow settings to be store in secrets and azure

---

Xero.Api/Core/Model/TaxComponent.cs

Add support for non-recoverable tax components that have recently been added to the API: https://developer.xero.com/documentation/api/tax-rates

Add IsNonRecoverable field to TaxComponent

---

Xero.Api/Serialization/DefaultMapper.cs

Includes support for nullable ManualJournalStatus

Allow nullable LineAmountTypes to be serialized correctly. 

---

Xero.Api/Payroll/AmericanPayroll.cs
Xero.Api/Payroll/AustralianPayroll.cs
Xero.Api/Payroll/Common/PayrollApi.cs

Added overload for setting the XeroApiSettings on Payroll APIs

---

README.md

it was a bit misleading + the dotnet core command was wrong

Update the installation part

---

Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
Xero.NetStandard.OAuth2Client/src/Models/Tenant.cs

There were just some date properties missing from the Tenant Id

Added Date Properties to the Tenant

---

Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj

corrected package version name

updated the package version number

---

README.md
Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs
Xero.NetStandard.OAuth2Client/src/Models/Tenant.cs

Added disconnection function to delete a connection by passing in accessToken and a Tenant object. 
Tenant type now supports TenantName.

added disconnect method & tenantName to Xero.NetStandard.OAuth2.Client

---

README.md
Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
Xero.NetStandard.OAuth2Client/src/Client/IXeroClient.cs
Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs
Xero.NetStandard.OAuth2Client/src/Models/Tenant.cs

Added methods for OAuth 2.0 PCKE flow:
- BuildLoginUriPkce(string codeVerifier)
- RequestAccessTokenPkceAsync(string code, string codeVerifier)

Support for PCKE flow

---

README.md
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Model/PayrollAu/LeaveType.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj

LeaveType.cs
- corrected LeaveLoadingRate date type from int to double

Payroll Au, LeaveType's LeaveLoadingRate changed from int to double

---

Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
Xero.NetStandard.OAuth2Client/src/Models/Tenant.cs

fixed error caused by authEventId being null by making it nullable.

authEventId is now nullable

---

Xero.NetStandard.OAuth2/Client/ApiClient.cs
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj

As per requested by: 
https://github.com/XeroAPI/Xero-NetStandard/issues/198
https://github.com/XeroAPI/Xero-NetStandard/issues/126

restsharp version updated to 106.11.4

---

Xero.NetStandard.OAuth2/Api/AccountingApi.cs
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj

getPurchaseOrdersAttachments
getPurchaseOrderAttachmentByFileName
updatePurchaseOrderAttachmentByFileName
createPurchaseOrderAttachmentByFileName

added purchase order attachment methods

---

Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Model/Accounting/ReportFields.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj

This PR will fix issues raised [here](https://github.com/XeroAPI/Xero-NetStandard/issues/265).

updated FieldID from uuid to string

---

README.md

Added following examples: 
- Create a bankfeed connection
- Get all bankfeed connections
- Delete a bankfeed connection
- Create statements against a bankfeed connection
- Get all statements from all bankfeed connections

Add bankfeed API methods to readme

---

.github/workflows/dotnet.yml

- only run on release publish
- remove extra commands
- publish real SDK

Tidy up dotnet.yml

---

Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
Xero.NetStandard.OAuth2Client/src/Client/IXeroClient.cs
docs/accounting/index.html
docs/bankfeeds/index.html
docs/files/index.html
docs/payroll-au/index.html
docs/payroll-nz/index.html
docs/payroll-uk/index.html
docs/projects/index.html

Bug fix to export the new method

Client credentials export

---

README.md
Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj

Big upgrade for the readme/docs. Links more sample apps, examples, OAuth2 flow, and custom connections Instructions.

README change for Custom Connections aka client credentials

---

Xero.NetStandard.OAuth2/Client/ApiException.cs
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
docs/accounting/index.html
docs/appstore/index.html
docs/bankfeeds/index.html
docs/files/index.html
docs/finance/index.html
docs/payroll-au/index.html
docs/payroll-nz/index.html
docs/payroll-uk/index.html
docs/projects/index.html

In the event the API rate limit is hit and a status code 429 response from Xero, the ApiException returned now includes `RetryAfter` and `LimitType`.
Shout out to @Itamaram for calling out the issue and collaborating on the fix!

Retry after fix

---

Xero.NetStandard.OAuth2.Test/Xero.NetStandard.OAuth2.Test.csproj
Xero.NetStandard.OAuth2/Client/ApiClient.cs
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Client/IReadableConfiguration.cs
Xero.NetStandard.OAuth2/Client/RequestOptions.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj

There were some big changes to RestSharp in the 107 version. I've updated support to 108 in this PR.
It talks a lot about the code is meant to be autogenerated so not sure if this was the correct way to do this. We have built this locally and its working for us.

RestSharp 108 support

---

Xero.NetStandard.OAuth2.Test/Api/AccountingApiTests.cs
Xero.NetStandard.OAuth2.Test/Api/BankFeedsApiTests.cs
Xero.NetStandard.OAuth2.Test/Api/PayrollAuApiTests.cs
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
docs/accounting/index.html
docs/appstore/index.html
docs/bankfeeds/index.html
docs/files/index.html
docs/finance/index.html
docs/payroll-au/index.html
docs/payroll-nz/index.html
docs/payroll-uk/index.html
docs/projects/index.html

Doc version got updated
Dotnet Test procedure is broken and is too far behind. It will need a separate branch and testing.
Due to this, the Github action for auto uploading to Nuget was not working with 3.34.0 as the build and test stage isn't completely working.
The build should work now with the manual change to the test code in 3.34.1.

Dotnet Test no longer works, will need update

---

README.md
Xero.NetStandard.OAuth2.Test/Api/AccountingApiTests.cs
Xero.NetStandard.OAuth2.Test/Api/PayrollAuApiTests.cs
Xero.NetStandard.OAuth2.Test/appsettings.json
Xero.NetStandard.OAuth2.Test/util/start-prism.sh
Xero.NetStandard.OAuth2/Api/AccountingApi.cs
Xero.NetStandard.OAuth2/Api/FinanceApi.cs
Xero.NetStandard.OAuth2/Api/PayrollNZApi.cs
Xero.NetStandard.OAuth2/Api/PayrollUkApi.cs
Xero.NetStandard.OAuth2/Api/ProjectApi.cs
Xero.NetStandard.OAuth2/Model/PayrollNz/Employee.cs
Xero.NetStandard.OAuth2/Model/PayrollNz/Employment.cs
Xero.NetStandard.OAuth2/Model/PayrollUk/Employee.cs
Xero.NetStandard.OAuth2/Model/PayrollUk/Employment.cs
docs/accounting/index.html
docs/appstore/index.html
docs/assets/index.html
docs/payroll-au/index.html
docs/payroll-nz/index.html
docs/payroll-uk/index.html
docs/projects/index.html

PETOSS-561 Update existing tests in Dotnet SDK to work with PRISM Mock Server

---

Xero.NetStandard.OAuth2.Test/Xero.NetStandard.OAuth2.Test.csproj
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj

Reverts XeroAPI/Xero-NetStandard#588

Revert "ECOOI-6890 Fix Vulnerable Packages"

---

.github/actions/notify-slack/action.yml
.github/workflows/dotnet.yml

https://xero.atlassian.net/browse/PETOSS-733
https://xero.atlassian.net/browse/CAB-5505

PETOSS 733 | Automation | SDK pipeline | Enable the SDK publish pipeline

---

Xero.NetStandard.OAuth2/Client/ApiClient.cs
Xero.NetStandard.OAuth2/Client/Configuration.cs
Xero.NetStandard.OAuth2/Xero.NetStandard.OAuth2.csproj
docs/accounting/index.html
docs/appstore/index.html
docs/bankfeeds/index.html
docs/files/index.html
docs/finance/index.html
docs/payroll-au/index.html
docs/payroll-nz/index.html
docs/payroll-uk/index.html
docs/projects/index.html

This addresses a regression introduced in v9.0.0
Fixes #563

[PETOSS-609] Make InterceptRequest and InterceptResponse protected virtual
